[project]
name = "music-cleaning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "pydub>=0.25.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
